### PR TITLE
Toggl API migration v8 to v9

### PR DESCRIPTION
**Pull request by nparrag**
This change is [Reviewable](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5)

### CODE REVIEW

**Review by nparrag — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nparrag)

**Review by nbali — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5)* status: all files reviewed, 2 unresolved discussions (waiting on @nparrag)

___
*[`src/toggl_to_jira_sync/actions.py` line 27 at r2](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5#-Nz_f_el74kWDe3n0imT:-Nz_f_em1IEqr9hAzZlv:b9gns98) ([raw file](https://github.com/aliz-ai/toggl-to-jira-sync/blob/e5ce1341b052e194a23b26fec45546daac3bb685/src/toggl_to_jira_sync/actions.py#L27)):*
> ```Python
>         self._jira_delete = False
>         self._jira_create = False
>         self._toggl_workspace_id = toggl_workspace_id
> ```

I love it how the ordering is totally random :D
___
*[`src/toggl_to_jira_sync/apis.py` line 71 at r2](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5#-Nz_hjqvApcbsqy7P3AV:-Nz_hjqvApcbsqy7P3AW:b-hybf89) ([raw file](https://github.com/aliz-ai/toggl-to-jira-sync/blob/e5ce1341b052e194a23b26fec45546daac3bb685/src/toggl_to_jira_sync/apis.py#L71)):*
> ```Python
> 
>     def get_workspaces(self):
>         return self._get("v9/workspaces")
> ```

isn't it `v9/me/workspaces`?
___
*[`src/toggl_to_jira_sync/apis.py` line 131 at r2](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5#-Nz_h4JF9X3gxCc9CL9u:-Nz_h4JF9X3gxCc9CL9v:btirxnc) ([raw file](https://github.com/aliz-ai/toggl-to-jira-sync/blob/e5ce1341b052e194a23b26fec45546daac3bb685/src/toggl_to_jira_sync/apis.py#L131)):*
> ```Python
> 
>     def _get_entry(self, id):
>         return self._get("v9/me/time_entries/{id}".format(id=id))
> ```

this is `time_entry_id` now, be consistent

**Review by nparrag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @nbali)

___
*[`src/toggl_to_jira_sync/apis.py` line 71 at r2](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5#-Nz_hjqvApcbsqy7P3AV:-O5xC5MZ6yL3UrKNrIiO:b-cwgvru) ([raw file](https://github.com/aliz-ai/toggl-to-jira-sync/blob/e5ce1341b052e194a23b26fec45546daac3bb685/src/toggl_to_jira_sync/apis.py#L71)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

isn't it `v9/me/workspaces`?
</blockquote></details>

Based on this, it is good:
https://engineering.toggl.com/docs/additional/v8_migration_guide
___
*[`src/toggl_to_jira_sync/apis.py` line 131 at r2](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5#-Nz_h4JF9X3gxCc9CL9u:-O5xEHhi3NlhJ7VgsBim:b-896fix) ([raw file](https://github.com/aliz-ai/toggl-to-jira-sync/blob/e5ce1341b052e194a23b26fec45546daac3bb685/src/toggl_to_jira_sync/apis.py#L131)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

this is `time_entry_id` now, be consistent
</blockquote></details>

Done.

**Review by nbali — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5)* status: all files reviewed, 1 unresolved discussion (waiting on @nparrag)

___
*[`src/toggl_to_jira_sync/actions.py` line 31 at r4](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5#-O5xkvHbDKXiLHJaiKkq:-O5xkvHbDKXiLHJaiKkr:bptwtkt) ([raw file](https://github.com/aliz-ai/toggl-to-jira-sync/blob/a0a40e671abd0cc0fd37657353d102a6b607a430/src/toggl_to_jira_sync/actions.py#L31)):*
> ```Python
>         self._toggl_id = toggl_id
>         self._toggl_updates = dict()
>         self._toggl_workspace_id = toggl_workspace_id
> ```

I'm not sure I get the logic behind this reordering
___
*[`src/toggl_to_jira_sync/apis.py` line 71 at r2](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5#-Nz_hjqvApcbsqy7P3AV:-O5xkL3Y6xdFFfW-r_EF:b-xi6njq) ([raw file](https://github.com/aliz-ai/toggl-to-jira-sync/blob/e5ce1341b052e194a23b26fec45546daac3bb685/src/toggl_to_jira_sync/apis.py#L71)):*
<details><summary><i>Previously, nparrag (Norbert Parrag) wrote…</i></summary><blockquote>

Based on this, it is good:
https://engineering.toggl.com/docs/additional/v8_migration_guide
</blockquote></details>

actually I was right about being suspicious

**Review by nparrag — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5)* status: all files reviewed, 1 unresolved discussion (waiting on @nbali)

___
*[`src/toggl_to_jira_sync/actions.py` line 31 at r4](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5#-O5xkvHbDKXiLHJaiKkq:-O60Loef5lSBkekX1XbF:b32vin) ([raw file](https://github.com/aliz-ai/toggl-to-jira-sync/blob/a0a40e671abd0cc0fd37657353d102a6b607a430/src/toggl_to_jira_sync/actions.py#L31)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

I'm not sure I get the logic behind this reordering
</blockquote></details>

:D

**Review by nbali — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5)* status: all files reviewed, 1 unresolved discussion (waiting on @nparrag)

___
*[`src/toggl_to_jira_sync/actions.py` line 31 at r4](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5#-O5xkvHbDKXiLHJaiKkq:-O6MlI8a5v6Qnw5WOMZJ:bk4jvhy) ([raw file](https://github.com/aliz-ai/toggl-to-jira-sync/blob/a0a40e671abd0cc0fd37657353d102a6b607a430/src/toggl_to_jira_sync/actions.py#L31)):*
<details><summary><i>Previously, nparrag (Norbert Parrag) wrote…</i></summary><blockquote>

:D
</blockquote></details>

I mean I complained about being random, and you just made it to another random order if you compare it with the parameter list :D

**Review by gmazak — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5)* status: all files reviewed, 1 unresolved discussion (waiting on @nparrag)

**Review by gmazak — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/toggl-to-jira-sync/5)* status: all files reviewed, 1 unresolved discussion (waiting on @nparrag)

**Pull request merged**
